In [2]:
!pip install numpy

   ---------------------------------------- 0.0/15.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.9 MB 2.4 MB/s eta 0:00:07
   ---- ----------------------------------- 1.8/15.9 MB 5.0 MB/s eta 0:00:03
   -------- ------------------------------- 3.4/15.9 MB 5.8 MB/s eta 0:00:03
   ----------- ---------------------------- 4.7/15.9 MB 5.9 MB/s eta 0:00:02
   --------------- ------------------------ 6.0/15.9 MB 6.0 MB/s eta 0:00:02
   ------------------- -------------------- 7.9/15.9 MB 6.4 MB/s eta 0:00:02
   ---------------------- ----------------- 8.9/15.9 MB 6.2 MB/s eta 0:00:02
   ----------------------- ---------------- 9.2/15.9 MB 5.9 MB/s eta 0:00:02
   ------------------------ --------------- 9.7/15.9 MB 5.4 MB/s eta 0:00:02
   -------------------------- ------------- 10.5/15.9 MB 5.0 MB/s eta 0:00:02
   ----------------------------- ---------- 11.8/15.9 MB 5.1 MB/s eta 0:00:01
   --------------------------------- ------ 13.4/15.9 MB 5.2 MB/s eta 0:00:01
   

In [2]:
import numpy as np

In [3]:
data = np.load('eeg_imagenet40_cvpr_2017_raw/train/n02106662_1152_1.npy',allow_pickle=True)
data

array([array([[[192, 222, 255],
               [192, 222, 255],
               [193, 222, 255],
               ...,
               [189, 214, 255],
               [189, 214, 254],
               [189, 214, 254]],

              [[191, 221, 255],
               [191, 221, 255],
               [192, 221, 255],
               ...,
               [189, 214, 254],
               [189, 214, 254],
               [189, 215, 252]],

              [[191, 221, 255],
               [191, 221, 255],
               [191, 221, 255],
               ...,
               [189, 214, 254],
               [190, 216, 253],
               [190, 216, 253]],

              ...,

              [[205, 173, 122],
               [210, 186, 142],
               [221, 198, 166],
               ...,
               [111,  96,  93],
               [ 83,  68,  63],
               [ 89,  74,  67]],

              [[227, 207, 170],
               [222, 198, 174],
               [206, 176, 142],
               ...,
        

In [14]:
data.shape

(5,)

In [16]:
data[0].shape

(333, 500, 3)

In [17]:
data[1].shape

(128, 440)

In [19]:
data[2]

np.int64(12)

In [21]:
data[3]

'n02106662_1152'

In [22]:
data[4]

np.int64(1)

In [6]:
import numpy as np
import os
from glob import glob

train_folder = 'eeg_imagenet40_cvpr_2017_raw/train'

npy_files = glob(os.path.join(train_folder, '*.npy'))

# 음수 값 확인
for file in npy_files:
    data = np.load(file, allow_pickle=True)
    if data[1].min() < 0:
        print(f"음수 ㅇ: {file}")
        print(data[1][data[1] < 0])
    else:
        print(f"음수 x: {file}")

음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10232_1.npy
[  -111.   -115.   -112. ...   -688. -17258.  -1998.]
음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10232_2.npy
[  -5. -140. -658. ... -102.   -2. -647.]
음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10232_3.npy
[  -28.   -52.   -25. ...  -177. -2119. -1301.]
음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10232_4.npy
[  -7.   -1.   -3. ... -112. -241.  -64.]
음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10232_5.npy
[ -33. -101.  -22. ... -193. -110. -324.]
음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10232_6.npy
[-132.  -85.  -38. ... -307. -437. -124.]
음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10432_1.npy
[  -35.   -36.   -17. ...  -146. -4458. -4170.]
음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10432_2.npy
[  -6.   -3.   -4. ... -168. -241. -165.]
음수 ㅇ: eeg_imagenet40_cvpr_2017_raw/train\n02106662_10432_3.npy
[  -21.  -103.   -32. ... -8741. -1762. -1424.]
음수 ㅇ: eeg_imagenet40_cvpr

KeyboardInterrupt: 